export const ADD_COINS_STOCK = "ADD_COINS_STOCK";
export const EDIT_COINS_STOCK = "EDIT_COINS_STOCK";
export const DELETE_COINS_STOCK = "DELETE_COINS_STOCK";
export const UPDATE_COINS_STOCK_NUMBER_OF_ITEMS = "UPDATE_COINS_STOCK_NUMBER_OF_ITEMS";